#!/bin/bash
ROOT_PATH=/BIGDATA/nsccgz_pcheng_1/src/WorkflowSim-1.0
java -cp $ROOT_PATH/dist/lib/WorkflowSim.jar:$ROOT_PATH/lib/flanagan.jar:$ROOT_PATH/lib/jdom-2.0.0.jar:$ROOT_PATH/lib/commons-math3-3.2.jar:.  GeneticAlgorithmTest $ROOT_PATH/config/dax/Epigenomics_100.xml
